### ISSUE TITLE
.lufr to .nirs issues

### ISSUE THREAD

**Issue by zrsoleimani** [Gowerlabs/lumomat#56]
Hi ,
I got some warnings while converting .lufr to .nirs for some of my data points:

Warning: The specified LUFR file contains incomplete frames. Consult the frame error
counter to determine those frames for which the data is incomplete. Note that missing
data will present as NaN in the associated data structure

Warning: Layout ID (0x0000012b) does not match group ID (0x0000012a), enumeration may be inconsistent

I'm wondering what each warning means. does that mean the data point has some problems and it is not usable? and Can I do anything to fix it?

Any help would be appreciated!

**Comment by Giuseppe-1993** [comment]
Hi @zrsoleimani, 

The warnings you received are due to the following conditions:

**Incomplete frames:** Under times of high system load, it is possible that the operating system is unable to service the USB interface as quickly as necessary. This can result in the occasional missing frame, where the data are replaced with NaN. As part of your processing pipeline, you should take the necessary steps to account for NaNs, such as discarding the missing frames if they not required for analysis or interpolating them if they are needed.

**Layout ID mismatch:** The warning you received suggests that the ID reported by the cap and the one included in the layout file are not the same. This could happen if you specified an alternative layout file when you loaded the data; what command did you use to load the file? If you believe that this was not done intentionally, could you please open a support ticket by emailing support@gowerlabs.co.uk so that we can inspect the data?

I hope this helps to understand the warnings.

**Comment by zrsoleimani** [comment]
Thank you so much @Giuseppe-1993. it was very helpful.

**Comment by samuelpowell** [comment]
This issue appears resolved, please reopen if that is not the case.
